AY2425S1-CS2103T-W08-1/tp

docs/DeveloperGuide.md
=> Edit value proposition for Developer Guide

docs/DeveloperGuide.md
=> Update DG to include non-functional requirement and glossary

docs/AboutUs.md, docs/DeveloperGuide.md
=> Edit target user profile in developer guide

docs/AboutUs.md
=> Add Samson AboutUs page

docs/AboutUs.md, docs/team/waihongteh.md
=> Edit AboutUs.md for Wai Hong

docs/AboutUs.md
=> Update AboutUs for Jing Min

docs/DeveloperGuide.md
=> Refine Glossary and NFR of DG

src/main/java/seedu/address/logic/commands/DeleteCommand.java, src/test/java/seedu/address/logic/LogicManagerTest.java
=> Update delete student command

src/main/java/seedu/address/model/tut/Tut.java, src/test/java/seedu/address/model/student/TutTest.java, src/test/java/seedu/address/model/tut/TutTest.java, src/test/java/seedu/address/testutil/TutUtil.java
=> Add Tut class

src/main/java/seedu/address/commons/util/FileUtil.java, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/commands/FindCommand.java, src/main/java/seedu/address/logic/commands/exceptions/CommandException.java, src/main/java/seedu/address/logic/parser/AddCommandParser.java, src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java, src/main/java/seedu/address/logic/parser/CliSyntax.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/student/PresentDates.java, src/main/java/seedu/address/model/student/Student.java, src/main/java/seedu/address/model/tut/TutDate.java, src/main/java/seedu/address/model/util/SampleDataUtil.java, src/main/java/seedu/address/storage/JsonAdaptedPresentDates.java, src/main/java/seedu/address/storage/JsonAdaptedStudent.java, src/main/java/seedu/address/storage/JsonAdaptedTutDate.java, src/main/java/seedu/address/storage/StorageManager.java, src/test/java/seedu/address/logic/commands/EditStudentDescriptorTest.java, src/test/java/seedu/address/storage/JsonAdaptedStudentTest.java, src/test/java/seedu/address/testutil/EditStudentDescriptorBuilder.java, src/test/java/seedu/address/testutil/StudentBuilder.java, src/test/java/seedu/address/testutil/TypicalStudents.java, src/test/java/seedu/address/ui/UiPartTest.java
=> Add record student attendance feature

src/main/java/seedu/address/logic/commands/DeleteAssignmentCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/DeleteAssignmentCommandParser.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/assignment/AssignmentList.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java, src/test/java/seedu/address/logic/commands/DeleteAssignmentCommandTest.java, src/test/java/seedu/address/logic/commands/DeleteCommandTest.java, src/test/java/seedu/address/logic/parser/DeleteAssignmentCommandPaserTest.java, src/test/java/seedu/address/testutil/TypicalAssignments.java
=> Delete assignment feature

src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/commands/AddTutCommand.java, src/main/java/seedu/address/logic/parser/AddTutCommandParser.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/CliSyntax.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/AddressBook.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/tut/Tut.java, src/main/java/seedu/address/model/tut/exceptions/TutNoFoundException.java, src/test/java/seedu/address/logic/commands/AddTutCommandTest.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/parser/AddTutCommandParserTest.java, src/test/java/seedu/address/model/AddressBookTest.java, src/test/java/seedu/address/model/tut/TutTest.java, src/test/java/seedu/address/testutil/TutUtil.java
=> Branch 1009 add tut

src/main/java/seedu/address/logic/commands/AddAssignmentCommand.java, src/main/java/seedu/address/logic/commands/CheckAssignmentCommand.java, src/main/java/seedu/address/logic/commands/ListAssignmentCommand.java, src/main/java/seedu/address/logic/commands/MarkAssignmentCommand.java, src/main/java/seedu/address/logic/commands/UnmarkAssignmentCommand.java, src/main/java/seedu/address/model/assignment/Assignment.java, src/main/java/seedu/address/model/assignment/AssignmentList.java, src/test/java/seedu/address/logic/commands/AddAssignmentCommandTest.java, src/test/java/seedu/address/logic/commands/CheckAssignmentCommandTest.java, src/test/java/seedu/address/logic/commands/DeleteAssignmentCommandTest.java, src/test/java/seedu/address/logic/commands/ListAssignmentCommandTest.java, src/test/java/seedu/address/logic/commands/MarkAssignmentCommandTest.java, src/test/java/seedu/address/logic/commands/UnmarkAssignmentCommandTest.java, src/test/java/seedu/address/logic/parser/AddAssignmentCommandParserTest.java, src/test/java/seedu/address/logic/parser/CheckAssignmentCommandParserTest.java, src/test/java/seedu/address/logic/parser/DeleteAssignmentCommandPaserTest.java, src/test/java/seedu/address/logic/parser/MarkAssignmentCommandParserTest.java, src/test/java/seedu/address/logic/parser/UnmarkAssignmentCommandParserTest.java, src/test/java/seedu/address/model/assignment/AssignmentListTest.java, src/test/java/seedu/address/model/assignment/AssignmentTest.java, src/test/java/seedu/address/testutil/TypicalAssignments.java
=> Add test cases for assignments

src/main/java/seedu/address/logic/commands/DeleteTutorialCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/DeleteTutorialCommandParser.java, src/main/java/seedu/address/model/AddressBook.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/tut/Tut.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java, src/test/java/seedu/address/logic/commands/AddTutCommandTest.java, src/test/java/seedu/address/logic/commands/DeleteTutorialCommandTest.java, src/test/java/seedu/address/logic/parser/DeleteTutorialCommandParserTest.java, src/test/java/seedu/address/model/ModelManagerTest.java
=> Delete tutorial feature

src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/parser/AddCommandParser.java, src/main/java/seedu/address/logic/parser/AddTutCommandParser.java, src/main/java/seedu/address/logic/parser/DeleteTutorialCommandParser.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/student/TutorialClass.java, src/main/java/seedu/address/model/tut/Tutorial.java, src/main/java/seedu/address/model/tut/TutorialList.java, src/main/java/seedu/address/model/tut/exceptions/NoTutorialException.java, src/main/java/seedu/address/storage/JsonAdaptedStudent.java, src/main/java/seedu/address/storage/JsonAdaptedTutorial.java, src/main/java/seedu/address/ui/StudentCard.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java, src/test/java/seedu/address/logic/commands/AttendCommandTest.java, src/test/java/seedu/address/logic/commands/DeleteTutorialCommandTest.java, src/test/java/seedu/address/logic/parser/AttendCommandParserTest.java, src/test/java/seedu/address/logic/parser/ParserUtilTest.java, src/test/java/seedu/address/model/ModelManagerTest.java, src/test/java/seedu/address/model/tut/TutorialListTest.java, src/test/java/seedu/address/model/tut/TutorialTest.java, src/test/java/seedu/address/storage/JsonAdaptedTutorialTest.java, src/test/java/seedu/address/storage/JsonSerializableTutorialListTest.java, src/test/java/seedu/address/storage/JsonTutorialStorageTest.java, src/test/java/seedu/address/testutil/EditStudentDescriptorBuilder.java, src/test/java/seedu/address/testutil/StudentBuilder.java, src/test/java/seedu/address/testutil/StudentUtil.java, src/test/java/seedu/address/testutil/TutUtil.java, src/test/java/seedu/address/testutil/TypicalTutorials.java
=> Delete feature bug

docs/diagrams/BetterModelClassDiagram2.puml, docs/diagrams/ModelClassDiagram2.puml, docs/diagrams/ParserClasses2.puml, docs/diagrams/StorageClassDiagram2.puml
=> Add UML diagram in model, storage

docs/UserGuide.md
=> Add user guide structure

docs/diagrams/ModelClassDiagram2.puml
Add Exist and None classes to Tutorial and TutorialClass to UML class diagram and class diagram 2
ModelClassDiagram
After:
Before:
BetterModelClassDiagram2
Before:
After:
=> Add Exist and None to Tutorial UML

docs/diagrams/DeleteAssignmentActivityDiagram.puml, docs/diagrams/DeleteSequenceDiagram.puml
=> Update UML diagram

docs/diagrams/BetterModelClassDiagram.puml, docs/diagrams/ModelClassDiagram.puml, docs/diagrams/StorageClassDiagram.puml
=> Arrange UML diagram to correct file

src/main/java/seedu/address/logic/parser/AddCommandParser.java, src/test/java/seedu/address/logic/parser/AddCommandParserTest.java, src/test/java/seedu/address/testutil/TypicalStudents.java
=> Add in handling of no tut for add stu

src/main/java/seedu/address/logic/commands/UnattendCommand.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/logic/parser/UnattendCommandParser.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/student/TutorialId.java, src/main/java/seedu/address/storage/JsonAdaptedStudent.java, src/main/java/seedu/address/storage/JsonAdaptedTutorial.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java, src/test/java/seedu/address/logic/commands/AttendCommandTest.java, src/test/java/seedu/address/logic/commands/EditStudentDescriptorTest.java, src/test/java/seedu/address/logic/parser/AddTutorialCommandParserTest.java, src/test/java/seedu/address/logic/parser/AttendCommandParserTest.java, src/test/java/seedu/address/logic/parser/UnattendCommandParserTest.java, src/test/java/seedu/address/model/ModelManagerTest.java, src/test/java/seedu/address/model/tut/TutorialListTest.java, src/test/java/seedu/address/model/tut/TutorialTest.java, src/test/java/seedu/address/storage/JsonAdaptedTutorialTest.java, src/test/java/seedu/address/testutil/StudentBuilder.java, src/test/java/seedu/address/testutil/StudentUtil.java
=> Change all tutorialClass to tutorialId

build.gradle, src/main/java/seedu/address/logic/commands/ListTutorialCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/tut/TutorialList.java, src/test/java/seedu/address/logic/commands/AddAssignmentCommandTest.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java, src/test/java/seedu/address/logic/commands/AddTutorialCommandTest.java, src/test/java/seedu/address/logic/commands/AttendCommandTest.java, src/test/java/seedu/address/logic/commands/ListTutorialCommandTest.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java, src/test/java/seedu/address/model/tut/TutorialListTest.java
=> Add listTut Command

src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/student/Student.java, src/main/java/seedu/address/model/tut/TutorialList.java, src/test/java/seedu/address/logic/LogicManagerTest.java, src/test/java/seedu/address/logic/commands/AddAssignmentCommandTest.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java, src/test/java/seedu/address/logic/commands/AddTutorialCommandTest.java, src/test/java/seedu/address/logic/commands/AttendCommandTest.java
=> Solve edit command bug

docs/_markbind/layouts/default.md, docs/site.json
=> Update title suffix

src/main/java/seedu/address/ui/HelpWindow.java
=> Update help command url

src/main/java/seedu/address/model/tut/TutorialList.java
=> Debug delete tutorial command

src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/commands/ClearCommand.java, src/main/java/seedu/address/logic/commands/DeleteAssignmentCommand.java, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/commands/MarkAssignmentCommand.java, src/main/java/seedu/address/logic/parser/AddAssignmentCommandParser.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/MarkAssignmentCommandParser.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/assignment/Assignment.java, src/main/java/seedu/address/model/assignment/AssignmentList.java, src/main/java/seedu/address/model/tut/Tutorial.java, src/test/java/seedu/address/logic/commands/AddAssignmentCommandTest.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java, src/test/java/seedu/address/logic/commands/AddTutorialCommandTest.java, src/test/java/seedu/address/logic/commands/AttendCommandTest.java, src/test/java/seedu/address/logic/commands/DeleteAssignmentCommandTest.java, src/test/java/seedu/address/logic/commands/MarkAssignmentCommandTest.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java, src/test/java/seedu/address/logic/parser/MarkAssignmentCommandParserTest.java, src/test/java/seedu/address/logic/parser/ParserUtilTest.java, src/test/java/seedu/address/model/ModelManagerTest.java, src/test/java/seedu/address/model/assignment/AssignmentListTest.java
Closes #163 
Closes #157 
Closes #148 
Closes #137
Closes #145 
Closes #146
=> Solve assignment bugs

src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/model/ModelManager.java, src/test/java/seedu/address/logic/commands/EditCommandTest.java, src/test/java/seedu/address/model/ModelManagerTest.java, src/test/java/seedu/address/testutil/TypicalStudents.java
=> Resolve edit command

docs/UserGuide.md, docs/diagrams/AttendCommandSequenceDiagram.puml, docs/site.json, src/main/java/seedu/address/logic/commands/AttendCommand.java, src/main/java/seedu/address/logic/commands/UnattendCommand.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/student/PresentDates.java, src/main/java/seedu/address/model/tut/TutDate.java, src/test/java/seedu/address/logic/commands/AttendCommandTest.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java, src/test/java/seedu/address/logic/parser/AttendCommandParserTest.java, src/test/java/seedu/address/logic/parser/UnattendCommandParserTest.java, src/test/java/seedu/address/testutil/TutUtil.java
=> Sort present dates

docs/UserGuide.md, docs/diagrams/AttendCommandSequenceDiagram.puml, src/main/java/seedu/address/logic/commands/AttendCommand.java, src/main/java/seedu/address/logic/commands/UnattendCommand.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/student/StudentId.java, src/main/java/seedu/address/model/tut/TutDate.java, src/test/java/seedu/address/logic/commands/AttendCommandTest.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java, src/test/java/seedu/address/logic/parser/AttendCommandParserTest.java, src/test/java/seedu/address/logic/parser/UnattendCommandParserTest.java, src/test/java/seedu/address/testutil/TutUtil.java
closes #147 
closes #149 
closes #158 
closes #161 
closes #164 
closes #165
closes #167 
closes #178
=> Fix Attend Command Bugs

src/main/java/seedu/address/logic/commands/DeleteAssignmentCommand.java, src/main/java/seedu/address/logic/commands/DeleteTutorialCommand.java, src/main/java/seedu/address/logic/parser/AddTutCommandParser.java, src/main/java/seedu/address/logic/parser/DeleteAssignmentCommandParser.java, src/main/java/seedu/address/logic/parser/DeleteTutorialCommandParser.java, src/test/java/seedu/address/logic/parser/DeleteAssignmentCommandPaserTest.java, src/test/java/seedu/address/logic/parser/DeleteTutorialCommandParserTest.java
=> Add prefix for delete tutorial and assignment command

docs/UserGuide.md
=> Update user guide on add command

src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/model/student/StudentId.java, src/main/java/seedu/address/model/student/UniqueStudentList.java, src/test/java/seedu/address/logic/LogicManagerTest.java, src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java, src/test/java/seedu/address/model/student/UniqueStudentListTest.java
closes #154 
closes #189
closes #160
=> Refine add command 

src/main/java/seedu/address/logic/LogicManager.java, src/main/java/seedu/address/logic/commands/CheckAssignmentCommand.java, src/main/java/seedu/address/model/assignment/AssignmentList.java, src/main/java/seedu/address/model/student/Student.java, src/main/java/seedu/address/ui/ResultDisplay.java, src/main/java/seedu/address/ui/StudentCard.java, src/main/resources/view/DarkTheme.css, src/main/resources/view/LightTheme.css, src/main/resources/view/MainWindow.fxml, src/main/resources/view/ResultDisplay.fxml, src/main/resources/view/StudentListCard.fxml, src/test/java/seedu/address/logic/commands/CheckAssignmentCommandTest.java, src/test/java/seedu/address/model/student/StudentTest.java
Student cards will now turn color when checkAsg command is used. Green for done, red for not done.
Make help window responsive based on the text length.
=> Update UI for student cards and help window

docs/UserGuide.md, src/main/java/seedu/address/logic/parser/CliSyntax.java, src/test/java/seedu/address/logic/parser/AddTutorialCommandParserTest.java
=> Bug fix#170

docs/UserGuide.md, docs/diagrams/UiClassDiagram.puml, src/main/java/seedu/address/logic/parser/CliSyntax.java, src/main/java/seedu/address/ui/MainWindow.java, src/main/java/seedu/address/ui/StudentCard.java, src/main/java/seedu/address/ui/StudentListPanel.java, src/test/java/seedu/address/logic/parser/AddTutorialCommandParserTest.java
=> Update dev guide

docs/UserGuide.md
- edit glossary
- correct grammatical error
closes #208
=> User guide update (glossary & minor error)

docs/diagrams/AddTutorialSequenceDiagram.puml
=> AddTutorialSequenceDiagram

src/main/java/seedu/address/ui/ResultDisplay.java
=> Remove unwanted println

docs/DeveloperGuide.md, docs/UserGuide.md, docs/diagrams/AddFeatureActivityDiagram.puml, docs/diagrams/AddFeatureClassDiagram.puml, docs/diagrams/ArchitectureSequenceDiagram.puml, docs/diagrams/DeleteSequenceDiagram.puml
closes #221 
closes #226 
closes #228 
closes #230 
closes #237 
closes #238 
closes #244
=> Solve alpha bug for Developer Guide

src/main/java/seedu/address/logic/commands/DeleteCommand.java, src/main/java/seedu/address/ui/StudentListPanel.java, src/main/java/seedu/address/ui/StudentProfile.java
If the student selected is deleted, the profile will be set to empty and the selection will be cleared.
Closes #216
=> Solve bug on student selection

docs/DeveloperGuide.md
=> Update developer guide delete format

docs/UserGuide.md
=> Update user guide command format

src/main/java/seedu/address/logic/commands/DeleteAssignmentCommand.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/assignment/AssignmentList.java, src/test/java/seedu/address/logic/commands/AddAssignmentCommandTest.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java, src/test/java/seedu/address/logic/commands/AddTutorialCommandTest.java, src/test/java/seedu/address/logic/commands/AttendCommandTest.java, src/test/java/seedu/address/model/ModelManagerTest.java, src/test/java/seedu/address/model/assignment/AssignmentListTest.java
=> Debug result display for delete assignment

docs/_markbind/layouts/default.md
=> Update markbind navigation

docs/UserGuide.md
=> User Guide update

build.gradle, docs/DeveloperGuide.md, docs/UserGuide.md, docs/diagrams/AttendCommandSequenceDiagram.puml, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/student/PresentDates.java, src/main/java/seedu/address/model/student/Student.java
closes #370 
closes #369 
closes #363 
closes #361 
closes #362 
closes #321 
closes #320 
closes #316 
closes #314
closes #310 
closes #303 
closes #294 
closes #292 
closes #289 
closes #287 
closes #281 
closes #280 
closes #279
=> Fix PE dry run bugs

docs/DeveloperGuide.md, docs/UserGuide.md
Closes #291 
Closes #295 
Closes #296 
Closes #297
Closes #300 
Closes #325 
Closes #304
=> Debug PE documentation link

src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/student/PresentDates.java, src/main/java/seedu/address/model/tut/TutDate.java
=> Fix edit bug related to mark attendance

src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/parser/AddAssignmentCommandParser.java, src/main/java/seedu/address/logic/parser/CheckAssignmentCommandParser.java, src/main/java/seedu/address/logic/parser/DeleteAssignmentCommandParser.java, src/main/java/seedu/address/logic/parser/MarkAssignmentCommandParser.java, src/main/java/seedu/address/logic/parser/UnmarkAssignmentCommandParser.java, src/test/java/seedu/address/logic/parser/AddAssignmentCommandParserTest.java, src/test/java/seedu/address/logic/parser/CheckAssignmentCommandParserTest.java, src/test/java/seedu/address/logic/parser/DeleteAssignmentCommandPaserTest.java, src/test/java/seedu/address/logic/parser/MarkAssignmentCommandParserTest.java, src/test/java/seedu/address/logic/parser/UnmarkAssignmentCommandParserTest.java
This PR fixes functionality bug as stated in #367. Refer to the comment for the rationale behind why it is a functionality bug if needed.
Closes #367
=> Fix empty assignment issue

docs/UserGuide.md
=> Update edit command in UG

docs/UserGuide.md
=> Debug the documentation error

src/main/java/seedu/address/logic/parser/ParserUtil.java
=> Fix attendance date format bug
